### PR TITLE
refactor(sdk): aux client

### PR DESCRIPTION
**Pull request by lidatong**
This refactors the AuxClient constructor to be easier to use and closer to self-documenting.

```typescript
const auxClient = new AuxClient("mainnet", new AptosClient("https://fullnode.mainnet.aptoslabs.com/v1"))
const auxClient = new AuxClient("devnet", new AptosClient("https://fullnode.devnet.aptoslabs.com/v1"))

const auxClient = new AuxClient("mainnet", new AptosClient("http://localhost:8080"))

import { env } from "./env";
const auxClient = new AuxClient("mainnet", env().aptosClient)
```

It now resembles what you might see in Ethereum or Solana's`web3` sdks:
```typescript
// eth
const web3 = new Web3(Web3.givenProvider || "ws://localhost:8545");

// eth
const provider = new ethers.providers.JsonRpcProvider('https://mainnet.infura.io/v3/<YOUR-ENDPOINT-HERE>')

// sol
const connection = new Connection("https://solana-api.projectserum.com");
```

After creating the connection in the L1's `web3` SDK, you then pass that `Connection` object directly to the protocol's SDK (composition via "_dependency injection_" vs. something more akin to "_service locator_").
```typescript
// serum
import { Connection } from '@solana/web3.js';
import { Market } from '@project-serum/serum';

const connection = new Connection('https://testnet.solana.com');
const market = await Market.load(connection, ...);

// uniswap
const provider = new ethers.providers.JsonRpcProvider('https://mainnet.infura.io/v3/<YOUR-ENDPOINT-HERE>')
const poolContract = new ethers.Contract(poolAddress, IUniswapV3PoolABI, provider)

// pyth
const connection = new Connection("https://solana-api.projectserum.com");
const pythPublicKey = getPythProgramKeyForCluster("mainnet-beta");
export const pythConnection = new PythConnection(connection, pythPublicKey);
```

For convenience, there is a helper function to parse your `~/.aptos/config.yaml` file. For example, this might be useful for setting Full Node REST urls:
 
```yaml
 mainnet:
     rest_url: http://localhost:8080
```
```typescript
const aptosNetwork = process.env["APTOS_NETWORK"];
const profile = getAptosProfile(aptosNetwork);
const auxClient = new AuxClient("mainnet", new AptosClient(profile.rest_url);
```

### CODE REVIEW

**Comment by fardream** [comment]
> This refactors the AuxClient constructor to be easier to use and closer to self-documenting.
> 
> ```ts
> const auxClient = new AuxClient("mainnet")  // uses "https://fullnode.mainnet.aptoslabs.com/v1"
> ```

Is the string `"mainnet"` here an aptos network? or it is a profile name? does this allow use a different profile name if it is a network name?

Also, storing profile at `$HOME/.aptos/config.yaml` is no the default behavior of aptos cli.

**Comment by lidatong** [comment]
> > This refactors the AuxClient constructor to be easier to use and closer to self-documenting.
> > ```ts
> > const auxClient = new AuxClient("mainnet")  // uses "https://fullnode.mainnet.aptoslabs.com/v1"
> > ```
> 
> Is the string `"mainnet"` here an aptos network? or it is a profile name? does this allow use a different profile name if it is a network name?
> 
> Also, storing profile at `$HOME/.aptos/config.yaml` is no the default behavior of aptos cli.

Yep, you're right. It's ambiguous. I think the right way to go here is that "aptosNetwork" is the Aptos Network.

I was thinking more about this and I think responsibility of creating the connection should be extracted from the SDK. The wiring should not be done automatically by the constructor. The `AptosClient` should be explicitly created and passed in to the constructor. This would more closely match what familiar DeFi SDKs do (e.g. UniswapV3, Serum, Pyth).

Our scripts / services can still make use of the profile loaders as helpers (see `env()`). External users can optionally also use them -- I've documented that it assumes you have configured Aptos config to be in your home folder.

**Comment by lidatong** [comment]
Made the naming more explicit (e.g. `aptosNetwork` vs. `network`) and added some documentation

**Comment by yuhanfang** [comment]
This looks reasonable. Looks like mainly refactoring the constructor-related stuff and some renaming?

Not for this PR, but are you still thinking of going ahead with the new pool/market interfaces?

**Comment by lidatong** [comment]
> This looks reasonable. Looks like mainly refactoring the constructor-related stuff and some renaming?
> 
> Not for this PR, but are you still thinking of going ahead with the new pool/market interfaces?

Yeah, I've been dogfooding the SDK and my sense is making everything constructor-based `new AuxClient(...), new Pool(...), new Market(...)` will simplify the usage. And yep, those are up next!

**Review by yuhanfang — APPROVED** [review]

**Pull request merged**
